# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    driver: "gd"
    default_filter_set_settings:
        format: webp
    webp:
        generate: true
    resolvers :
        default :
            web_path : ~
    filter_sets :
        cache : ~
        logo_thumbnail_jpeg:
            format: jpeg
            quality: 80
            filters:
                thumbnail: { size: [ 50, 50 ], mode: inset }
        logo_thumbnail_webp:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [ 50, 50 ], mode: inset }
