services:
  postgresql:
    image: 'postgres:9.6.22'
    container_name: rda-pgsql
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
    ports:
      - "13004:5432"

  redis:
    image: 'redis:latest'
    container_name: rda-redis
    ports:
      - "13005:6379"
