<?php

declare(strict_types=1);

namespace App\Enum;

/** @author Alexandre Tomatis <alexandre.tomatis@gmail.com> */
final class County
{
    // ISO 3166-2:FR (https://fr.wikipedia.org/wiki/ISO_3166-2:FR)
    const FR_01 = 'FR-01';
    const FR_02 = 'FR-02';
    const FR_03 = 'FR-03';
    const FR_04 = 'FR-04';
    const FR_05 = 'FR-05';
    const FR_06 = 'FR-06';
    const FR_07 = 'FR-07';
    const FR_08 = 'FR-08';
    const FR_09 = 'FR-09';
    const FR_10 = 'FR-10';
    const FR_11 = 'FR-11';
    const FR_12 = 'FR-12';
    const FR_13 = 'FR-13';
    const FR_14 = 'FR-14';
    const FR_15 = 'FR-15';
    const FR_16 = 'FR-16';
    const FR_17 = 'FR-17';
    const FR_18 = 'FR-18';
    const FR_19 = 'FR-19';
    const FR_2A = 'FR-2A';
    const FR_2B = 'FR-2B';
    const FR_21 = 'FR-21';
    const FR_22 = 'FR-22';
    const FR_23 = 'FR-23';
    const FR_24 = 'FR-24';
    const FR_25 = 'FR-25';
    const FR_26 = 'FR-26';
    const FR_27 = 'FR-27';
    const FR_28 = 'FR-28';
    const FR_29 = 'FR-29';
    const FR_30 = 'FR-30';
    const FR_31 = 'FR-31';
    const FR_32 = 'FR-32';
    const FR_33 = 'FR-33';
    const FR_34 = 'FR-34';
    const FR_35 = 'FR-35';
    const FR_36 = 'FR-36';
    const FR_37 = 'FR-37';
    const FR_38 = 'FR-38';
    const FR_39 = 'FR-39';
    const FR_40 = 'FR-40';
    const FR_41 = 'FR-41';
    const FR_42 = 'FR-42';
    const FR_43 = 'FR-43';
    const FR_44 = 'FR-44';
    const FR_45 = 'FR-45';
    const FR_46 = 'FR-46';
    const FR_47 = 'FR-47';
    const FR_48 = 'FR-48';
    const FR_49 = 'FR-49';
    const FR_50 = 'FR-50';
    const FR_51 = 'FR-51';
    const FR_52 = 'FR-52';
    const FR_53 = 'FR-53';
    const FR_54 = 'FR-54';
    const FR_55 = 'FR-55';
    const FR_56 = 'FR-56';
    const FR_57 = 'FR-57';
    const FR_58 = 'FR-58';
    const FR_59 = 'FR-59';
    const FR_60 = 'FR-60';
    const FR_61 = 'FR-61';
    const FR_62 = 'FR-62';
    const FR_63 = 'FR-63';
    const FR_64 = 'FR-64';
    const FR_65 = 'FR-65';
    const FR_66 = 'FR-66';
    const FR_67 = 'FR-67';
    const FR_68 = 'FR-68';
    const FR_69 = 'FR-69';
    const FR_70 = 'FR-70';
    const FR_71 = 'FR-71';
    const FR_72 = 'FR-72';
    const FR_73 = 'FR-73';
    const FR_74 = 'FR-74';
    const FR_75 = 'FR-75';
    const FR_76 = 'FR-76';
    const FR_77 = 'FR-77';
    const FR_78 = 'FR-78';
    const FR_79 = 'FR-79';
    const FR_80 = 'FR-80';
    const FR_81 = 'FR-81';
    const FR_82 = 'FR-82';
    const FR_83 = 'FR-83';
    const FR_84 = 'FR-84';
    const FR_85 = 'FR-85';
    const FR_86 = 'FR-86';
    const FR_87 = 'FR-87';
    const FR_88 = 'FR-88';
    const FR_89 = 'FR-89';
    const FR_90 = 'FR-90';
    const FR_91 = 'FR-91';
    const FR_92 = 'FR-92';
    const FR_93 = 'FR-93';
    const FR_94 = 'FR-94';
    const FR_95 = 'FR-95';
    const FR_974 = 'FR-974';


    private const map = [
        self::FR_01 => 'Ain',
        self::FR_02 => 'Aisne ',
        self::FR_03 => 'Allier',
        self::FR_04 => 'Alpes-de-Haute-Provence',
        self::FR_05 => 'Hautes-Alpes',
        self::FR_06 => 'Alpes-Maritimes',
        self::FR_07 => 'Ardèche',
        self::FR_08 => 'Ardennes',
        self::FR_09 => 'Ariège',
        self::FR_10 => 'Aube',
        self::FR_11 => 'Aude',
        self::FR_12 => 'Aveyron',
        self::FR_13 => 'Bouches-du-Rhône',
        self::FR_14 => 'Calvados',
        self::FR_15 => 'Cantal',
        self::FR_16 => 'Charente',
        self::FR_17 => 'Charente-Maritime',
        self::FR_18 => 'Cher',
        self::FR_19 => 'Corrèze',
        self::FR_2A => 'Corse-du-Sud',
        self::FR_2B => 'Haute-Corse',
        self::FR_21 => 'Côte-d’Or',
        self::FR_22 => 'Côtes-d’Armor',
        self::FR_23 => 'Creuse',
        self::FR_24 => 'Dordogne',
        self::FR_25 => 'Doubs',
        self::FR_26 => 'Drôme',
        self::FR_27 => 'Eure',
        self::FR_28 => 'Eure-et-Loir',
        self::FR_29 => 'Finistère',
        self::FR_30 => 'Gard',
        self::FR_31 => 'Haute-Garonne',
        self::FR_32 => 'Gers',
        self::FR_33 => 'Gironde',
        self::FR_34 => 'Hérault',
        self::FR_35 => 'Ille-et-Vilaine',
        self::FR_36 => 'Indre',
        self::FR_37 => 'Indre-et-Loire',
        self::FR_38 => 'Isère',
        self::FR_39 => 'Jura',
        self::FR_40 => 'Landes',
        self::FR_41 => 'Loir-et-Cher',
        self::FR_42 => 'Loire',
        self::FR_43 => 'Haute-Loire',
        self::FR_44 => 'Loire-Atlantique',
        self::FR_45 => 'Loiret',
        self::FR_46 => 'Lot',
        self::FR_47 => 'Lot-et-Garonne',
        self::FR_48 => 'Lozère',
        self::FR_49 => 'Maine-et-Loire',
        self::FR_50 => 'Manche',
        self::FR_51 => 'Marne',
        self::FR_52 => 'Haute-Marne',
        self::FR_53 => 'Mayenne',
        self::FR_54 => 'Meurthe-et-Moselle',
        self::FR_55 => 'Meuse',
        self::FR_56 => 'Morbihan',
        self::FR_57 => 'Moselle',
        self::FR_58 => 'Nièvre',
        self::FR_59 => 'Nord',
        self::FR_60 => 'Oise',
        self::FR_61 => 'Orne',
        self::FR_62 => 'Pas-de-Calais',
        self::FR_63 => 'Puy-de-Dôme',
        self::FR_64 => 'Pyrénées-Atlantiques',
        self::FR_65 => 'Hautes-Pyrénées ',
        self::FR_66 => 'Pyrénées-Orientales',
        self::FR_67 => 'Bas-Rhin',
        self::FR_68 => 'Haut-Rhin',
        self::FR_69 => 'Rhône',
        self::FR_70 => 'Haute-Saône',
        self::FR_71 => 'Saône-et-Loire',
        self::FR_72 => 'Sarthe',
        self::FR_73 => 'Savoie',
        self::FR_74 => 'Haute-Savoie',
        self::FR_75 => 'Arrondissement de Paris',
        self::FR_76 => 'Seine-Maritime',
        self::FR_77 => 'Seine-et-Marne',
        self::FR_78 => 'Yvelines',
        self::FR_79 => 'Deux-Sèvres',
        self::FR_80 => 'Somme',
        self::FR_81 => 'Tarn',
        self::FR_82 => 'Tarn-et-Garonne',
        self::FR_83 => 'Var',
        self::FR_84 => 'Vaucluse',
        self::FR_85 => 'Vendée',
        self::FR_86 => 'Vienne',
        self::FR_87 => 'Haute-Vienne',
        self::FR_88 => 'Vosges',
        self::FR_89 => 'Yonne',
        self::FR_90 => 'Territoire de Belfort',
        self::FR_91 => 'Essonne',
        self::FR_92 => 'Hauts-de-Seine',
        self::FR_93 => 'Seine-Saint-Denis',
        self::FR_94 => 'Val-de-Marne',
        self::FR_95 => 'Val-d’Oise',
        self::FR_974 => 'La Réunion',
    ];

    /** @param string $countyCode ISO 3166-2:FR */
    static function getName(string $countyCode): string
    {
        return self::map[$countyCode];
    }
}
